// Voice — every user-facing string in one place.
//
// The TEXT lives in ./copy.en.json (the single flat file you read + edit). This module is
// a thin typed loader over it: plain strings pass through; runtime values are filled by a
// tiny {placeholder} formatter (see ./format.ts); accent headlines stay {lead, em, tail}.
// Components import `copy` and its shape is unchanged — editing a word is a JSON-only change,
// and a locale (messages/de.json …) is a later drop-in reading window.nimiqPay.language.
//
// Brand-derived values (the wordmark / brand name) come from ./brand.ts, not the copy file,
// so the name has one source of truth.

import type { Asset } from '../vault/types.ts'
import { brand } from './brand.ts'
import { fmt } from './format.ts'
import en from './copy.en.json'

export interface Headline {
  lead?: string
  em: string
  tail?: string
}

export const copy = {
  app: {
    wordmark: brand.name,
    recon: en.app.recon,
    test: en.app.test,
  },

  gate: {
    kicker: en.gate.kicker,
    h1: en.gate.h1 as Headline,
    sub: en.gate.sub,
    invitedKicker: (creator: string) => fmt(en.gate.invitedKicker, { creator }),
    invitedSub: en.gate.invitedSub,
    expiredKicker: en.gate.expiredKicker,
    expiredH1: en.gate.expiredH1 as Headline,
    expiredSub: en.gate.expiredSub,
    expiredOpen: en.gate.expiredOpen,
    open: en.gate.open,
    reassure: en.gate.reassure,
    get: en.gate.get,
    foot: en.gate.foot,
  },

  create: {
    resumeGo: en.create.resumeGo,
    kicker: en.create.kicker,
    h1: en.create.h1 as Headline,
    sub: en.create.sub,
    customLabel: en.create.customLabel,
    customPlaceholder: en.create.customPlaceholder,
    durationLabel: en.create.durationLabel,
    daysUnit: en.create.daysUnit,
    stakeLabel: en.create.stakeLabel,
    stakeNote: en.create.stakeNote,
    windowLabel: en.create.windowLabel,
    testWindowNote: en.create.testWindowNote,
    nameLabel: en.create.nameLabel,
    namePlaceholder: en.create.namePlaceholder,
    cta: (stake: number, asset: Asset) => fmt(en.create.cta, { stake, asset }),
    ctaBusy: en.create.ctaBusy,
    errFallback: en.create.errFallback,
    needGoal: en.create.needGoal,
    needName: en.create.needName,
  },

  pledged: {
    kicker: en.pledged.kicker,
    h1: en.pledged.h1 as Headline,
    sub: en.pledged.sub,
    share: en.pledged.share,
    inviteLead: en.pledged.inviteLead,
    invite: en.pledged.invite,
    inviteCopied: en.pledged.inviteCopied,
    goChallenge: en.pledged.goChallenge,
    preview: en.pledged.preview,
    notFoundH1: en.pledged.notFoundH1,
    notFoundSub: en.pledged.notFoundSub,
    notFoundCta: en.pledged.notFoundCta,
  },

  join: {
    kickerDared: (creator: string) => fmt(en.join.kickerDared, { creator }),
    h1Lead: en.join.h1Lead,
    h1: en.join.h1 as Headline,
    sub: en.join.sub,
    whosInOne: (a: string) => fmt(en.join.whosInOne, { a }),
    whosInTwo: (a: string, b: string) => fmt(en.join.whosInTwo, { a, b }),
    whosInMany: (a: string, b: string, extra: number) => fmt(en.join.whosInMany, { a, b, extra }),
    crewRunning: en.join.crewRunning,
    countdown: en.join.countdown,
    nameLabel: en.join.nameLabel,
    namePlaceholder: en.join.namePlaceholder,
    needName: en.join.needName,
    cta: (stake: number, asset: Asset) => fmt(en.join.cta, { stake, asset }),
    ctaBusy: en.join.ctaBusy,
    errCancel: en.join.errCancel,
    errFallback: en.join.errFallback,
    guarantee: en.join.guarantee,
    offerExit: en.join.offerExit,
    heldSafe: (stake: number, asset: Asset) => fmt(en.join.heldSafe, { stake, asset }),

    joinedKicker: en.join.joinedKicker,
    joinedH1: en.join.joinedH1 as Headline,
    joinedSub: (stake: number, asset: Asset) => fmt(en.join.joinedSub, { stake, asset }),
    youMake: (n: number) => fmt(en.join.youMake, { n }),
    reshareQuote: en.join.reshareQuote,
    pullFriend: en.join.pullFriend,
    pullFriendCopied: en.join.pullFriendCopied,
    later: en.join.later,

    closedH1: en.join.closedH1,
    closedSub: (creator: string, emoji: string) => fmt(en.join.closedSub, { creator, emoji }),
    closedCta: en.join.closedCta,
    closedFoot: (whosIn: string) => fmt(en.join.closedFoot, { whosIn }),

    notFoundH1: en.join.notFoundH1,
    notFoundSub: en.join.notFoundSub,
    notFoundCta: en.join.notFoundCta,
  },

  progress: {
    dayOf: (day: number, total: number) => fmt(en.progress.dayOf, { day, total }),
    startsKicker: en.progress.startsKicker,
    startsTitle: en.progress.startsTitle,
    startsSub: (t: string) => fmt(en.progress.startsSub, { t }),
    wrappedKicker: en.progress.wrappedKicker,
    windowLeft: (t: string) => fmt(en.progress.windowLeft, { t }),
    checkedTitle: en.progress.checkedTitle,
    checkedSub: (t: string) => fmt(en.progress.checkedSub, { t }),
    overTitle: en.progress.overTitle,
    overSub: en.progress.overSub,
    checkinLabel: en.progress.checkinLabel,
    checkinPlaceholder: en.progress.checkinPlaceholder,
    checkinCta: (day: number) => fmt(en.progress.checkinCta, { day }),
    checkinBusy: en.progress.checkinBusy,
    errFallback: en.progress.errFallback,
    doneTitle: en.progress.doneTitle,
    doneSub: en.progress.doneSub,
    crewLabel: en.progress.crewLabel,
    feedEmpty: en.progress.feedEmpty,
    feedDay: (day: number) => fmt(en.progress.feedDay, { day }),
    seeResults: en.progress.seeResults,
    shareLabel: en.progress.shareLabel,
    shareCta: en.progress.shareCta,
    notFoundH1: en.progress.notFoundH1,
    notFoundCta: en.progress.notFoundCta,
  },

  results: {
    kicker: (emoji: string, goal: string) => fmt(en.results.kicker, { emoji, goal }),
    h1Perfect: (unit: string) => ({ lead: en.results.h1Perfect.lead, em: fmt(en.results.h1Perfect.em, { unit }) }) as Headline,
    h1Landed: en.results.h1Landed as Headline,
    daysMeta: (done: number, total: number) => fmt(en.results.daysMeta, { done, total }),
    back: (asset: string) => fmt(en.results.back, { asset }),
    banked: (asset: string) => fmt(en.results.banked, { asset }),
    yoursKicker: en.results.yoursKicker,
    backPart: (amt: string, asset: string) => fmt(en.results.backPart, { amt, asset }),
    bonusPart: (amt: string, asset: string) => fmt(en.results.bonusPart, { amt, asset }),
    lostPart: (amt: string, asset: string) => fmt(en.results.lostPart, { amt, asset }),
    landed: en.results.landed,
    settling: en.results.settling,
    perfectBadgeTitle: en.results.perfectBadgeTitle,
    shareWin: en.results.shareWin,
    shareWrap: en.results.shareWrap,
    crewLabel: en.results.crewLabel,
    you: en.results.you,
    burnedSummary: (amt: string, asset: Asset) => fmt(en.results.burnedSummary, { amt, asset }),
    burnedSub: (finishers: number) => fmt(en.results.burnedSub, { finishers }),
    burnedTag: (amt: string) => fmt(en.results.burnedTag, { amt }),
    runItBack: en.results.runItBack,
    none: en.results.none,
    home: en.results.home,
  },

  // Text that rides along with a shared link / image.
  share: {
    pledge: (emoji: string, goal: string, days: number, stake: number, asset: Asset) =>
      fmt(en.share.pledge, { emoji, goal, days, stake, asset }),
    joined: (creator: string, emoji: string) => fmt(en.share.joined, { creator, emoji }),
    resultsWin: (emoji: string, goal: string, unit: string) => fmt(en.share.resultsWin, { emoji, goal, unit }),
    resultsWrap: (emoji: string) => fmt(en.share.resultsWrap, { emoji, brand: brand.name }),
    progress: (emoji: string, goal: string, day: number, total: number) =>
      fmt(en.share.progress, { emoji, goal, day, total }),
  },

  // ── The reshape (Cycle II) — the solo-first journey. Accent headlines keep
  // {lead, em, tail} as separate words so a locale can place the emphasis (§1.5).
  rs: {
    main: {
      kicker: en.rs.main.kicker,
      hLead: en.rs.main.hLead,
      hEm: en.rs.main.hEm,
      startedThisWeek: (n: number) => fmt(en.rs.main.startedThisWeek, { n: n.toLocaleString() }),
      cta: en.rs.main.cta,
    },
    taste: {
      hTop: en.rs.taste.hTop,
      hLead: en.rs.taste.hLead,
      hEm: en.rs.taste.hEm,
      hTail: en.rs.taste.hTail,
      hintPre: en.rs.taste.hintPre,
      hintEm: en.rs.taste.hintEm,
      hintPost: en.rs.taste.hintPost,
      exit: en.rs.taste.exit,
      cta: en.rs.taste.cta,
    },
    official: {
      hLead: en.rs.official.hLead,
      hEm: en.rs.official.hEm,
      sub: en.rs.official.sub,
      hintPre: en.rs.official.hintPre,
      hintEm: en.rs.official.hintEm,
      hintPost: en.rs.official.hintPost,
      perDayLabel: en.rs.official.perDayLabel,
      perDayUnit: en.rs.official.perDayUnit,
      lengthLabel: en.rs.official.lengthLabel,
      daysUnit: en.rs.official.daysUnit,
      backdateLead: en.rs.official.backdateLead,
      backdateBold: en.rs.official.backdateBold,
      needNim: (need: number) => fmt(en.rs.official.needNim, { need }),
      cta: en.rs.official.cta,
      busy: en.rs.official.busy,
      err: en.rs.official.err,
      errCancel: en.rs.official.errCancel,
      stamp: en.rs.official.stamp,
      contractWeek: en.rs.official.contractWeek,
      contractDaysN: (days: number) => fmt(en.rs.official.contractDaysN, { days }),
      contractNo: (no: string) => fmt(en.rs.official.contractNo, { no }),
    },
    seal: {
      kicker: en.rs.seal.kicker,
      hLead: en.rs.seal.hLead,
      cardTop: en.rs.seal.cardTop,
      cardBottom: en.rs.seal.cardBottom,
      cta: en.rs.seal.cta,
    },
    day: {
      streakPill: (n: number) => fmt(en.rs.day.streakPill, { n }),
      cta: en.rs.day.cta,
      sealing: en.rs.day.sealing,
      sealedKicker: (day: number) => fmt(en.rs.day.sealedKicker, { day }),
      onchain: en.rs.day.onchain,
      toGo: (n: number) => fmt(en.rs.day.toGo, { n }),
      lastSealed: en.rs.day.lastSealed,
      shareDay: (day: number) => fmt(en.rs.day.shareDay, { day }),
      err: en.rs.day.err,
    },
    banked: {
      kicker: en.rs.banked.kicker,
      hLead: en.rs.banked.hLead,
      moneyLbl: en.rs.banked.moneyLbl,
      gain: (n: number) => fmt(en.rs.banked.gain, { n }),
      rowStake: en.rs.banked.rowStake,
      rowBonus: en.rs.banked.rowBonus,
      rowBanked: en.rs.banked.rowBanked,
      goAgainWeek: en.rs.banked.goAgainWeek,
      shareWin: en.rs.banked.shareWin,
      kickerUp: en.rs.banked.kickerUp,
      hPartialLead: en.rs.banked.hPartialLead,
      hPartialTail: en.rs.banked.hPartialTail,
      partialNote: (kept: number, total: number) => fmt(en.rs.banked.partialNote, { kept, total, other: total - kept }),
      rowKept: (n: number) => fmt(en.rs.banked.rowKept, { n }),
      rowBurned: (n: number) => fmt(en.rs.banked.rowBurned, { n }),
      rowBack: en.rs.banked.rowBack,
      partialFwdLead: en.rs.banked.partialFwdLead,
      partialFwdBold: en.rs.banked.partialFwdBold,
      partialFwdTail: en.rs.banked.partialFwdTail,
      seeRecord: en.rs.banked.seeRecord,
      goAgainGoal: (label: string) => fmt(en.rs.banked.goAgainGoal, { label }),
      hWipeout: en.rs.banked.hWipeout,
      burnedLbl: en.rs.banked.burnedLbl,
      wipeoutNote: en.rs.banked.wipeoutNote,
      wipeoutFwdLead: en.rs.banked.wipeoutFwdLead,
      wipeoutFwdBold: en.rs.banked.wipeoutFwdBold,
      wipeoutFwdTail: en.rs.banked.wipeoutFwdTail,
      backHome: en.rs.banked.backHome,
      tryAgain: en.rs.banked.tryAgain,
    },
    reup: {
      kicker: en.rs.reup.kicker,
      hLead: en.rs.reup.hLead,
      hEm: en.rs.reup.hEm,
      sub: en.rs.reup.sub,
      recordNum: (n: number) => fmt(en.rs.reup.recordNum, { n }),
      pickNew: en.rs.reup.pickNew,
      anotherWeek: (label: string) => fmt(en.rs.reup.anotherWeek, { label }),
    },
    archive: {
      h: en.rs.archive.h,
      lead: en.rs.archive.lead,
      meta: (kept: number, total: number, stake: number, when: string) => fmt(en.rs.archive.meta, { kept, total, stake, when }),
      metaLapsed: en.rs.archive.metaLapsed,
      tagBanked: en.rs.archive.tagBanked,
      tagPartial: en.rs.archive.tagPartial,
      tagLapsed: en.rs.archive.tagLapsed,
      tagGone: en.rs.archive.tagGone,
      start: en.rs.archive.start,
      thisWeek: en.rs.archive.thisWeek,
      lastWeek: en.rs.archive.lastWeek,
    },
    missed: {
      hLead: en.rs.missed.hLead,
      sub: (slice: number, kept: number) => fmt(en.rs.missed.sub, { slice, tail: kept > 0 ? en.rs.missed.subKeptYes : en.rs.missed.subKeptNo }),
      hintPre: en.rs.missed.hintPre,
      hintEm: en.rs.missed.hintEm,
      hintPost: en.rs.missed.hintPost,
      cta: en.rs.missed.cta,
    },
    lapsed: {
      hLead: en.rs.lapsed.hLead,
      sub: en.rs.lapsed.sub,
      cta: en.rs.lapsed.cta,
    },
    perfectweek: {
      kicker: en.rs.perfectweek.kicker,
      hLead: en.rs.perfectweek.hLead,
      hEm: en.rs.perfectweek.hEm,
      sub: en.rs.perfectweek.sub,
      cta: en.rs.perfectweek.cta,
    },
    sphere: {
      tasteHint: { pre: en.rs.sphere.tasteHint.pre, em: en.rs.sphere.tasteHint.em, post: en.rs.sphere.tasteHint.post },
      pickCtx: (label: string, day: number) => fmt(en.rs.sphere.pickCtx, { label, day }),
      pickShare: en.rs.sphere.pickShare,
    },
    shareCard: {
      stampRecord: en.rs.shareCard.stampRecord,
      cta: en.rs.shareCard.cta,
      no: (no: string) => fmt(en.rs.shareCard.no, { no }),
    },
    proof: {
      pre: en.rs.proof.pre,
      brand: en.rs.proof.brand,
      post: en.rs.proof.post,
    },
  },

  // Accessibility labels (screen-reader only).
  a11y: {
    home: en.a11y.home,
    openSphere: en.a11y.openSphere,
    close: en.a11y.close,
  },

  // On-card lettering (pledge ticket + results card). Shared by the live DOM cards
  // and the canvas share-image renderer.
  cards: {
    brand: brand.name,
    pledgeMeta: en.cards.pledgeMeta,
    pledgeGoalLead: en.cards.pledgeGoalLead,
    pledgeGoalFallback: en.cards.pledgeGoalFallback,
    pledgeForDays: (days: number) => fmt(en.cards.pledgeForDays, { days }),
    pledgeOnLine: en.cards.pledgeOnLine,
    pledgeStamp: en.cards.pledgeStamp,
    pledgeStampSub: en.cards.pledgeStampSub,
    pledgeFoot: en.cards.pledgeFoot,
    ticketSignedBy: en.cards.ticketSignedBy,
    ticketSealed: en.cards.ticketSealed,
    ticketCta: en.cards.ticketCta as Headline,
    lockedIn: en.cards.lockedIn,
  },
}
